### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by kip2** [kip2/Recursion_BankingApp#1]
- [ ] Create HTML first page.
- [ ] Create HTML second page.
- [ ] Create HTML third page.
- [ ] Create HTML forth page.
- [ ] Create HTML fifth page.
- [ ] Create HTML sixth page.
- [ ] Setting the NameSpace.
- [ ] Class settings.
- [ ] Generate random numbers
- [ ] Instance creation from submitted information.
- [ ] Data reflection
- [ ] Template literal
- [ ] 2nd page complete
- [ ] Implementing alerts.
- [ ] Creating a with draw page(1)
- [ ] Creating a with draw page(2)
- [ ] Creating a with draw page(3)
- [ ] Creating a with draw page(4)
- [ ] Input confirmation.
- [ ] View input
- [ ] billsummation
- [ ] View previous page
- [ ] Create and view calculation boxes
- [ ] Calculating the maximum amount that can be withdraw.
- [ ] Display maximum amount that can be withdrawn.
- [ ] Withdrawals & Balance Updates
- [ ] DRY measures
- [ ] Creating a deposit page(1)
- [ ] Creating a deposit page(2)
- [ ] Creating a deposit page(3)
- [ ] Creating a deposit page(4)
- [ ] Create a Come back later page(1)
- [ ] Create a Come back later page(2)
- [ ] Create a Come back later page(3)
- [ ] Congratulation!

- [ ] Clicker Empire Game
- [ ] まずGithubで別にリポジトリを作成する
- [ ] 次に、そのリポジトリ上で何をするかをTODOリストの形に直すこと
